# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
command:
  print_pipeline_id:
    steps:
      - run: 
        command: |
            echo ${CIRCLE_WORKFLOW_ID}
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
    steps:
      - print_pipeline_id
  
      

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-env-vars:
    jobs:
      - save_hello_world_output
      